const PROFILR_LOGIN="user,admin:PROFILR_LOGIN"
const EDIT_PROFILE_PIC="user:EDIT_PROFILE_PIC"
const EDIT_PROFILE_COVER="user:EDIT_PROFILE_COVER"
const GET_ALL_USER="admin:GET_ALL_USER"
const SHARE_PROFILE="user:SHARE_PROFILE"
module.exports={
    PROFILR_LOGIN,
    EDIT_PROFILE_PIC,
    EDIT_PROFILE_COVER,
    GET_ALL_USER,
    SHARE_PROFILE
    
}